### ISSUE TITLE
Setup server hardware and OS installation

### ISSUE THREAD

**Issue by GeertJohan** [nulpunt/nulpunt#2]

**Comment by GeertJohan** [comment]
Made contact with another pirate that maintains the PPNL servers. Will update on reponse.

**Comment by GeertJohan** [comment]
Sadly, the pirate I contacted does not have enough free time to join this project. I'll not configure the server myself.

**Comment by GeertJohan** [comment]
Now setting up mirrored disks.

**Comment by yjb81** [comment]
ok,
bedankt

**Comment by GeertJohan** [comment]
New sysadmin, @Argure.
These issues are now being closed and re-created at the systems repo.
