### ISSUE TITLE
Manual merge controlle

### ISSUE THREAD

**Issue by GeertJohan** [nulpunt/nulpunt#256]
Ik moest voor de merge tussen #253  en #254 enkele regels handmatig mergen.

@matijse had een span weggehaald en de styling class daarvan verplaats naar parent node. Terwijl @thomasvanlankveld juist op die span ng-mouse\* attributen had toegevoegd.

Ik heb deze attributen naar de parent node verplaatst en de span verwijderd. Graag controlleren dat alles nogsteeds naar wens werkt.

**Comment by matijse** [comment]
Ja zo is prima!

2014-02-13 9:34 GMT+01:00 Geert-Johan Riemer notifications@github.com:

**Comment by GeertJohan** [comment]
Top!
